# Generated by Django 4.1.1 on 2022-09-10 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='images/')),
                ('description', models.CharField(max_length=400)),
                ('location', models.CharField(max_length=120)),
            ],
        ),
    ]
