# Generated by Django 4.1.1 on 2022-09-10 17:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='asian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='indian',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suggestion',
            name='western',
            field=models.BooleanField(default=False),
        ),
    ]
