# Generated by Django 4.1.1 on 2022-09-10 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_suggestion_asian_suggestion_indian_suggestion_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 12, 40, 0, 733537)),
        ),
    ]
