# Generated by Django 4.1.1 on 2022-09-10 18:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_suggestion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
