# Generated by Django 4.1.1 on 2022-09-10 22:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_suggestion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
