# Generated by Django 4.1.1 on 2022-09-10 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_suggestion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suggestion',
            old_name='time',
            new_name='posttime',
        ),
    ]
