# Generated by Django 4.1.1 on 2022-09-10 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_time_suggestion_posttime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestion',
            name='posttime',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
